version: "3"
services:
  postgresql:
    image: "postgres" # use latest official postgres version
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=testdb
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/