apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
  - image: brianfiszman/go-from-zero-to-hero
deploy:
  helm:
    releases:
    - name: app
      chartPath: k8s
      wait: true
      useHelmSecrets: true
      valuesFiles:
      - ./k8s/values.yaml
      - ./k8s/secrets.yaml
      artifactOverrides:
        image: brianfiszman/go-from-zero-to-hero
      imageStrategy:
        helm: {}
