secrets:
    HTTP_PORT: ENC[AES256_GCM,data:6YZLgw==,iv:nCnIh/yyu9hN9PFZJSp8QGyvsQLDe2UPxGtv/ZomuUo=,tag:yQXen9Rcv9xOjr3ioBmXEA==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:/hSwDsx+P4hOqV7u9k0=,iv:9HDl1NfWTsHksCsE2xuIX66/4HQ55dusgIKsvgTDiY0=,tag:OwH5TO0LRVoDPNxLxV0ynA==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:ax59Ug==,iv:P8AE2MvATEKSanRfaBiyrGkoxS+yI9BX4DhxiHKADhw=,tag:y/ypynxyYHbQT/OWYAZ4NQ==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:PWOMzUe+kT4=,iv:0ryYHJs+pnCFvKKfevPdjUGIhIGNOJq4xpAda87G3ak=,tag:GGkMVjFJSKfE1zhgQlHSIA==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:q/wxSAGz,iv:cJF0ZT3Rx5qud3TyIUQea99LRzC7r7HXhqzLdUd4kDc=,tag:LPZmTwEYD86kdKPSjhUXPQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:inJwar5v,iv:LGr7M3oR1XoKfmUtKOyf/04jG1hcPy7RtzhJPcg4658=,tag:/6Sh3erdDgoRX131vKbLPg==,type:str]
    postgresql-password: ENC[AES256_GCM,data:g7h0r1u0,iv:ux0Sm6FjgH+5k9+7Zl49RMf3HW0++9n1qAx5famEX5c=,tag:XBgwg/sQ6KOxWxbWpeOhfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-26T19:20:28Z"
    mac: ENC[AES256_GCM,data:KvReKWOWnoCVF3+JitP7olFH/Rx6EwH14Yt8bXBCALH+xLvfrbKyihrAAawtD+NALkj5FczH1oD9/8w9ivOvLGzj0dK1Bm7ItVG/a9+huwqzuHQssr6yh1mabKiuMPDY+5mBNZYeWIHWBfmv1kHwuFADO1sWcclU7Egwh/ACRec=,iv:u3G4DGbVPNg3NxZqmI2RHrXftmq7tOybDGWR5WEJ3jg=,tag:zsKJh/wTCE4cLKiGyGelgQ==,type:str]
    pgp:
        - created_at: "2022-01-26T00:05:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DPdmMJfpzaQESAQdAngShZ8kkeq1PBNmorBy64BIomKmxDyEAlK4tspLbJmww
            KpFoj4b2h/4pJ/Zy7liu8F6RLUyreEvm4G2GGBMqvU7Z/fNr063TpQaz879Ia7NA
            0l4BjQvHEsH0UAKtXEBLNkfXLCAEo8xOKPxrIsSwxb8tWVsD9R3hx5fhme0eJ+vR
            9XTjkrWmCRWfiRzrUL12db029xZyk5t5+xjVdZMpPALbTdj3esCqqibv/hlgp3Hx
            =vUMV
            -----END PGP MESSAGE-----
          fp: 9CCFC90304A6E509
    unencrypted_suffix: _unencrypted
    version: 3.7.1
